src/java/UserController.java
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.context.ExternalContext;
import javax.servlet.ServletResponse;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import service.SABService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stanley
 */
@ManagedBean(name="usercontroller")
@RequestScoped
public class UserController {
    private ArrayList<User> users;
   
    private Connection connect;
    private Statement statement;
    private ResultSet resultset;
    private PreparedStatement preparedStatement;
    
    private String cookietype;
    private int cookieId;
    private String currentuser;
    
    private String url = "jdbc:mysql://localhost/";
    private String db = "wbdsimpleblog";
    private String dbuser = "root";
    private String dbpw = "";
    
    
    public ArrayList<User> getUsers() throws Exception{
        /*int nid;
        String nusername,npassword,nnama,nemail,ntipe;
        ArrayList<User> nusers=new ArrayList<>();
        User nuser;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection(url+db,dbuser,dbpw);
            statement = connect.createStatement();  
            resultset = statement.executeQuery("select * from user");
        }
        catch(Exception e){
        }
        
        while (resultset.next()){
            nid=resultset.getInt("id");
            nusername = resultset.getString("username");
            npassword = resultset.getString("password");
            ntipe = resultset.getString("tipe");
            nnama = resultset.getString("nama");
            nemail= resultset.getString("email");
            nuser = new User(nid,nusername,npassword,nnama,nemail,ntipe);
            nusers.add(nuser);
        }*/
        List<service.User> users = new ArrayList<>();
        ArrayList<User> nusers = new ArrayList<>();
        users = ServiceContainer.listUser();
        User usertoadd = new User();
        for (service.User u : users){
            nusers.add(new User(u));
        }        
        return nusers;
    } 
            
    public void addUsers(User U) throws Exception{
        /*FacesContext facesContext = FacesContext.getCurrentInstance();
        
        if(!U.isNull()){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver passed");
                connect = DriverManager.getConnection(url+db,dbuser,dbpw);
                        preparedStatement=connect.prepareStatement("INSERT INTO `user`(`id`,`username`,`password`,`nama`,`email`,`tipe`) "
                    + "VALUES (NULL,'"+U.getUsername()+"','"+U.getPassword()+"','"
                    +U.getNama()+"','"+U.getEmail()+"','"+U.getTipe()+"');");
                preparedStatement.executeUpdate();   
                ((HttpServletResponse) facesContext.getExternalContext().getResponse()).sendRedirect("manage.xhtml");
            }
            catch(Exception e){

            }
        }*/
        ServiceContainer.addUser(U.getUsername(), U.getPassword(), U.getNama(), U.getEmail(), U.getTipe());

    }
    
    public User getSpecifiedUser(String userid) {        
        User user = new User();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection(url+db,dbuser,dbpw);
            statement=connect.createStatement();
            resultset = statement.executeQuery("select * from user where `id`='"+userid+"';");           
            if(resultset.next()){
            user.setId(resultset.getString("id"));
            user.setUsername(resultset.getString("username"));
            user.setPassword(resultset.getString("password"));
            user.setNama(resultset.getString("nama"));
            user.setEmail(resultset.getString("email"));
            user.setTipe(resultset.getString("tipe"));
            }
        }
        catch (Exception e){
        }
        //User user = new User(ServiceContainer.getUser(userid));
        return user;
    }
    
    public void editUsers(User U) throws Exception{
        /*FacesContext facesContext = FacesContext.getCurrentInstance();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection(url+db,dbuser,dbpw);
            preparedStatement=connect.prepareStatement("UPDATE `user` SET `username`='"+U.getUsername()+"', `password`='"+U.getPassword()+"', "
                + "`nama`='"+U.getNama()+"', `email`='"+U.getEmail()+"', `tipe`='"+U.getTipe()+"' "
                + "WHERE `id`="+U.getId()+";");
            preparedStatement.executeUpdate();
            ((HttpServletResponse) facesContext.getExternalContext().getResponse()).sendRedirect("manage.xhtml");
            
        }
        catch(Exception e){
            System.out.println(e);
        }*/
        ServiceContainer.editUser(U.getId(), U.getNama(), U.getEmail(), U.getTipe());
    }

    
    public void deleteUsers(String userid) throws Exception{
        /*System.out.println(userid);
        FacesContext facesContext = FacesContext.getCurrentInstance();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection(url+db,dbuser,dbpw);
            preparedStatement=connect.prepareStatement("DELETE from user where id="+userid+";");
            preparedStatement.executeUpdate();
            System.out.println(userid + " deleted");
            ((HttpServletResponse) facesContext.getExternalContext().getResponse()).sendRedirect("manage.xhtml");
            connect.close();
        }
        catch(Exception e){
            
        }*/
        ServiceContainer.deleteUser(userid);
    }
    
    public String checkCookie() throws IOException{
        FacesContext facesContext=FacesContext.getCurrentInstance();
        String cookieuser=null;
        String cookiepass=null;
        String cookietipe=null;
        String retval=null;
        Cookie[] cookies=((HttpServletRequest)facesContext.getExternalContext().getRequest()).getCookies();
        
        for(int i=0;i<cookies.length;i++){
            if(cookies[i].getName().equalsIgnoreCase("currentuser")){
                cookieuser=cookies[i].getValue();
                System.out.println("cookieuser = "+cookieuser);
            }
            if(cookies[i].getName().equalsIgnoreCase("currentpass")){
                cookiepass=cookies[i].getValue();
                System.out.println("cookiepass = "+cookiepass);
            }
            if(cookies[i].getName().equalsIgnoreCase("currenttipe")){
                cookietipe=cookies[i].getValue();
                System.out.println("cookietipe = "+cookietipe);
            }
        }
        
        if(cookieuser!=null && cookiepass!=null){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                connect = DriverManager.getConnection(url+db,dbuser,dbpw);
                statement = connect.createStatement();
                resultset = statement.executeQuery("select * from user where username='"+cookieuser+"' and password='"+cookiepass+"';");
            }
            catch(Exception e){
                System.out.println("MASUK EXCEPTION");
            }
        }
        retval="blog.xhtml";
        System.out.println(retval);
        return retval;
    }
    
    public String getCookieUser(){
        String cookieuser=null;
        String retval=null;
        
        FacesContext facesContext = FacesContext.getCurrentInstance();
        Cookie[] cookies=((HttpServletRequest)facesContext.getExternalContext().getRequest()).getCookies();
        
        for(int i=0;i<cookies.length;i++){
            if(cookies[i].getName().equalsIgnoreCase("currentuser")){
                cookieuser=cookies[i].getValue();
                System.out.println("iduser = "+cookieuser);
            }
        }
        if(cookieuser!=null){
            retval=cookieuser;
        }
        else{
            retval="Guest";
        }
        return retval;
    }
    
    public String getCookieId(){
        String cookieid=null;
        String retval=null;
        
        FacesContext facesContext = FacesContext.getCurrentInstance();
        Cookie[] cookies=((HttpServletRequest)facesContext.getExternalContext().getRequest()).getCookies();
        
        for(int i=0;i<cookies.length;i++){
            if(cookies[i].getName().equalsIgnoreCase("currentid")){
                cookieid=cookies[i].getValue();
                System.out.println("iduser = "+cookieid);
            }
        }
        if(cookieid!=null){
            retval=cookieid;
        }
        return retval;
    }
    
    public String getCookieType(){
        String cookietipe=null;
        String retval=null;
        
        FacesContext facesContext = FacesContext.getCurrentInstance();
        Cookie[] cookies=((HttpServletRequest)facesContext.getExternalContext().getRequest()).getCookies();
        
        for(int i=0;i<cookies.length;i++){
            if(cookies[i].getName().equalsIgnoreCase("currenttipe")){
                cookietipe=cookies[i].getValue();
                System.out.println("cookieuser = "+cookietipe);
            }
        }
        if(cookietipe!=null){
            retval=cookietipe;
        }
        else{
            retval="Guest";
        }
        return retval;
    }
}

web/blog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<h:head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!--<script scr="main.js"></script>-->
        </link>
</h:head>
<body>
    <ui:include src="header.xhtml"/>
	<div id="POSTS">
            <ui:repeat var="post" value="#{postController.posts}">
		<div id="#{post.id}" class="post">	
                    <div class="title">
                                <a href="post.xhtml?pid=#{post.id}"><h1 id="postJudul">#{post.judul}
                                        </h1></a>
                                <h5 id="postTanggal">#{post.tanggal}</h5>
                            </div>
                    <div class="content"> <p id="postKonten"><h:outputText value="#{post.kontenFront}" escape="false"/></p>
                        <span style="display:#{postController.DelEditpublishedpost(usercontroller.cookieType)}"> 
                            <a href="editpost.xhtml?pid=#{post.id}"><button class="button">UBAH</button> </a> | 
                            <a onclick="deletePost('#{post.id}')"><button class="button" >HAPUS</button></a> 
                        </span>
                    </div>
		</div>
            </ui:repeat>
	</div>
	<script type="text/javascript">
		function deletePost(pid){
                    if (confirm("Apakah yakin ingin menghapus post ini?") === true) {
		       location.href = 'deletepost.xhtml?pid='+pid;
		    }
		};
	</script>
</body>
</html>

web/cookie.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
	<title>Baspram's Homepage</title>
	<link rel="stylesheet" type="text/css" href="resources/main.css"></link>
</head>
<body>
    <script>        
        window.location.href="#{usercontroller.checkCookie()}";
    </script>
</body>
</html>

web/deletedpost.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!--<script scr="main.js"></script>-->
        </link>
</h:head>
<h:body>
    <ui:include src="header.xhtml"/>
    <div id="FORM">
		<div id="POST">
                    #{post.Copy(postController.getSpecifiedPost(param['pid']))}
                    <h1>#{post.judul}</h1>
                    <h3>#{post.tanggal}<span>|</span><span class="unpublished"> Deleted </span></h3>
                    <p><h:outputText value="#{post.kontenHTML}" escape="false"/></p>
                    <div class="postbut">
                        <h:form>
                            <h:inputHidden value="#{post.id}"/>
                            <h:commandButton action="#{postController.PublishPost(post.id, true)}" class="button" value="RESTORE"/> |
                            <button onclick="deletePost(#{post.id})" class="button">REMOVE</button>
                        </h:form>
                    </div> 
                </div>
            <br></br>
                <div id="POSTS">
                    <h1>KOMENTAR</h1>
                    <h:form id="commentform">	
                        <h:panelGroup id="commentlist">
                            <ui:repeat var="item" value="#{postController.getComments(post.id)}">
                                <h:panelGroup class="post">
                                        <div class="postleft">
                                            <h1> <h:outputText value="#{item.nama}"/></h1>
                                            <h4> <h:outputText value="#{item.email}"/></h4>
                                            <p> <h:outputText value="#{item.tanggal}"/></p>
                                        </div>
                                        <div class="postright">
                                            <p> <h:outputText value="#{item.komen}"/></p>
                                        </div>
                                </h:panelGroup>
                            </ui:repeat>
                        </h:panelGroup>
                    </h:form>
                </div>
            </div>
</h:body>
	<script type="text/javascript">
		function deletePost(pid){
		    if (confirm("Apakah yakin ingin menghapus post ini? (tidak bisa di undo)") === true) {
		        location.href = 'removepost.xhtml?pid='+pid;
		    }
		};
	</script>
<!--<script type="text/javascript">
    function validation(){
        alert("ea");
    };
</script>-->
</html>

web/deletepost.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
	<title>Baspram's Homepage</title>
       <!-- <link rel="stylesheet" type="text/css" href="resources/main.css"></link>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script  scr="main.js"></script>-->
</head>
<body>
    #{postController.SoftDeletePost(param['pid'])}
    <script type="text/javascript">	
        window.location.href="blog.xhtml";
    </script>
</body>
</html>

web/editpost.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css"></link>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script  scr="main.js"></script>
</head>
<body>
    <ui:include src="header.xhtml"/>
    <div id="FORM"><h:form id="postform">
            #{post.Copy(postController.getSpecifiedPost(param['pid']))}
		<div id="EDITPOSTS">
                    <h:inputHidden id="pid" value="#{post.id}" />
		<h1>Edit Post</h1>
			<!--<form name="pos" method="post" onsubmit="validate()" action="blog.html">-->
            <div><label for="Judul">Judul</label>
                <h:inputText id="title" value="#{post.judul}"/>
            </div>
                            <br></br>
			<div>
            <label for="Tanggal">Tanggal</label>
            <h:inputText id="tanggal" value="#{post.tanggal}"/>
                        </div>
                            <br></br>
            <div>
                <label for="Konten">Konten</label><br></br>
            	<h:inputTextarea value="#{post.konten}" id="konten"/>
                <h:inputHidden value="#{post.status}"/>
			</div>
                            <br></br>
                            <h:commandButton class="button" onclick="return validate()" action="#{postController.EditPost(post)}" value="Simpan" />
                <!--</form>-->
                </div>
                            </h:form>
	</div>
    <script type="text/javascript">
        function validate(){
		var inputtanggal = document.getElementById('postform:tanggal').value;
		var istanggalformat = inputtanggal.search("[0-9]{4}-[0-9]{2}-[0-9]{2}");
		var judullength = document.getElementById('postform:title').value.length;
                var kontenlength = document.getElementById('postform:konten').value.length;
		var postdate=new Date(inputtanggal);
		var currenttime=new Date();
                if(kontenlength==0){
                    alert("konten post tidak boleh kosong");
                    return false;
                }
		if(judullength>35){
			alert("judul terlalu panjang(maks 35 karakter)");
			return false;
		}
		if(judullength==0){
			alert("judul tidak boleh kosong");
			return false;
		}
		if(istanggalformat=='0'){
			//alert("sampai sini");
			postdate.setHours(23);
			postdate.setMinutes(59);
			postdate.setSeconds(59);
			if(postdate >= currenttime){
				return true;
			}
			else{
				alert("tanggal tidak valid");
				return false;
			}
		}
		else{
			alert("format tanggal salah");
			return false;
		}
	}
     </script>
</body>
</html>

web/edituser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css"></link>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script  scr="main.js"></script>
</head>
<body>
    #{user.Copy(usercontroller.getSpecifiedUser(param['uid']))}
    <ui:include src="header.xhtml"/>
    <div id="FORM"><h:form>
		<div id="EDITPOSTS">
                    <h:inputHidden id="id" value="#{user.id}" />
                <h1>Manage User</h1>
			<h:form>
            <div><label for="username">Username</label>
                <h:inputText id="username" value="#{user.username}"></h:inputText>
            </div>
            <br></br>
            <div>
                <label for="password">Password</label>
                <h:inputText id="password" value="#{user.password}"></h:inputText>
            </div>
            <br></br>
            <div>
                <label for="nama">Nama</label>
                <h:inputText id="nama" value="#{user.nama}"></h:inputText>
            </div>
            <br></br>
            <div>
                <label for="email">E-mail</label>
                <h:inputText id="email" value="#{user.email}"></h:inputText>
            </div>
            <br></br>
            <div>
                <h:selectOneRadio required="true" value="#{user.tipe}" style="display: inline-block">
                    <f:selectItem itemValue="Admin" itemLabel="ADMIN" id="admin"/>        
                    <f:selectItem itemValue="Editor" itemLabel="EDITOR" id="editor"/>
                    <f:selectItem itemValue="Owner" itemLabel="OWNER" id="owner"/>
                </h:selectOneRadio>
            </div>
            <br></br>
            <h:commandButton class="button" action="#{usercontroller.editUsers(user)}" value="Simpan"/>
            </h:form>
		</div>
                            </h:form>
	</div>
	<!--<script type="text/javascript">
		function validate(){
			alert('Post telah ditambahkan');
			location.href = 'faces/cookie.xhtml';
		}
	</script>-->
</body>
</html>

web/post.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<h:head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!--<script scr="main.js"></script>-->
        </link>
</h:head>
<h:body>
    <ui:include src="header.xhtml"/>
    <div id="FORM">
		<div id="POST">
                    #{post.Copy(postController.getSpecifiedPost(param['pid']))}
                    <h1>#{post.judul}</h1>
                    <h3>#{post.tanggal}</h3>
                    <p><h:outputText value="#{post.konten}" escape="false"/></p>
                    <div class="postbut" style="display:#{postController.DelEditpublishedpost(usercontroller.cookieType)}"> 
                            <a href="editpost.xhtml?pid=#{post.id}"><button class="button">UBAH</button> </a> | 
                            <a onclick="deletePost(#{post.id})"><button class="button">HAPUS</button></a> 
                    </div> 
                </div>
            <br></br>
                <div id="POSTS">
                    <c:set var="user" value="#{usercontroller.getSpecifiedUser(usercontroller.cookieId)}"/>
                    <h:form h:name="commentform" id="commentform">	
                        #{comment.NewComment(user.username, user.email, "")}
                        <div id="comment_form">
                            <h1>KOMENTAR</h1>
                            <!--<form name="komen" method="post" return false;" >-->
                            <h:inputHidden value="#{post.id}" />
                            <label for="Nama">Nama:</label>
                            <h:inputText value="#{comment.nama}" id="nama" h:name="nama"/>
                            <label for="Email">Email:</label>
                            <h:inputText value="#{comment.email}" id="email" h:name="email"/>
                            <label for="Komentar">Komentar:</label><br></br>
                            <h:inputTextarea value="#{comment.komen}" rows="10" cols="20" id="komentar"/><br></br>
                            <h:commandButton  type="submit" onclick="return submitcomment()" class="button" value="Kirim">
                                <f:ajax id="ajax" execute="commentform" listener="#{postController.PostComment(comment, post.id)}"  render="comment_test" />
                            </h:commandButton>
                        </div>
                        <h:panelGroup id="comment_test">
                            <ui:repeat var="item" value="#{postController.getComments(post.id)}">
                                <h:panelGroup class="post">
                                        <div class="postleft">
                                            <h1> <h:outputText value="#{item.nama}"/></h1>
                                            <h4> <h:outputText value="#{item.email}"/></h4>
                                            <p> <h:outputText value="#{item.tanggal}"/></p>
                                        </div>
                                        <div class="postright">
                                            <p> <h:outputText value="#{item.komen}"/></p>
                                        </div>
                                </h:panelGroup>
                            </ui:repeat>
                        </h:panelGroup>
                    </h:form>
                </div>
            </div>
</h:body>
    <script type="text/javascript">
    function deletePost(pid){
        if (confirm("Apakah yakin ingin menghapus post ini?") === true) {
            location.href = 'deletepost.xhtml?pid='+pid;
        }
    }

    function submitcomment(){
        var inputemail = document.getElementById("commentform:email").value;
        var isemailvalid = inputemail.search("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
	var namelength = document.getElementById("commentform:nama").value.length;
	var kontenlength = document.getElementById("commentform:komentar").value.length;
        if(namelength>12){
		alert("nama terlalu panjang");
		return false;
	}
	if(namelength===0){
		alert("nama tidak boleh kosong");
		return false;
	}
	if(isemailvalid!='0' || inputemail.length>25){
		alert("email terlalu panjang atau tidak valid");
		return false;
	}
	if(kontenlength===0){
		alert("komentar tidak boleh kosong");
		return false;
	}
        return true;
    }
</script>
<!--<script type="text/javascript">
    function validation(){
        alert("ea");
    };
</script>-->
</html>

web/searchpage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<h:head>
	<title>The Blog</title>
        <link rel="stylesheet" type="text/css" href="resources/main.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!--<script scr="main.js"></script>-->
        </link>
</h:head>
<body>
    <ui:include src="header.xhtml"/>
	<div id="POSTS">
            <ui:repeat var="post" value="#{postController.SearchPost(param['keyword'])}">
		<div id="#{post.id}" class="post">	
                    <div class="title">
                                <a href="post.xhtml?pid=#{post.id}"><h1 id="postJudul">#{post.judul}
                                        </h1></a>
                                <h5 id="postTanggal">#{post.tanggal}</h5>
                            </div>
                    <div class="content"> <p id="postKonten"><h:outputText value="#{post.kontenFront}" escape="false"/></p>
                        <span style="display:#{postController.DelEditpublishedpost(usercontroller.cookieType)}"> 
                            <a href="editpost.xhtml?pid=#{post.id}"><button class="button">UBAH</button> </a> | 
                            <a onclick="deletePost(#{post.id})"><button class="button">HAPUS</button></a> 
                        </span>
                    </div>
		</div>
            </ui:repeat>
	</div>
</body>
	<script type="text/javascript">
		function deletePost(pid){
		    if (confirm("Apakah yakin ingin menghapus post ini?") === true) {
		        location.href = 'deletepost.xhtml?pid='+pid;
		    }
		};
	</script>    
</html>